import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const outputPath = resolve(process.cwd(), 'build-env.js');
const rawKey = process.env.MINIMAX_API_KEY || '';
const apiKey = rawKey.trim();

const content = `// Auto-generated by scripts/inject-env.mjs\nglobalThis.BUILD_MINIMAX_API_KEY = ${JSON.stringify(apiKey)};\n`;

writeFileSync(outputPath, content, 'utf8');
console.log('[inject-env] build-env.js updated');
